<script type="text/javascript" src="{{ URL::asset('assets/js/jquery-2.1.0.min.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('assets/js/jquery-migrate-1.2.1.min.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('assets/bootstrap/js/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('assets/js/smoothscroll.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('assets/js/owl.carousel.min.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('assets/js/bootstrap-select.min.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('assets/js/jquery.validate.min.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('assets/js/jquery.placeholder.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('assets/js/icheck.min.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('assets/js/jquery.vanillabox-0.1.5.min.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('assets/js/retina-1.1.0.min.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('assets/js/jshashtable-2.1_src.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('assets/js/jquery.numberformatter-1.2.3.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('assets/js/tmpl.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('assets/js/jquery.dependClass-0.1.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('assets/js/draggable-0.1.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('assets/js/jquery.slider.js') }}"></script>
<script type="text/javascript" src="{{ URL::asset('assets/js/custom.js') }}"></script>
@yield('script')